name: Update Git Tag from Go Version

on:
  push:
    branches:
      - main

jobs:
  update-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Extract version from skypiea.go
        id: get_version
        run: |
          version=$(grep -oP 'const version = "\K[^"]+' skypiea/skypiea.go)
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Versão extraída: $version"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "refs/tags/${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Tag ${{ env.VERSION }} já existe. Nenhuma ação necessária."
            exit 0
          fi

      - name: Create new tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
          echo "Nova tag criada: ${{ env.VERSION }}"